[pytest]
filterwarnings =
    ignore:'parseString' deprecated - use 'parse_string':DeprecationWarning
    ignore:'resetCache' deprecated - use 'reset_cache':DeprecationWarning
    ignore:'enablePackrat' deprecated - use 'enable_packrat':DeprecationWarning
    ignore:ast\.Num is deprecated and will be removed in Python 3\.14; use ast\.Constant instead:DeprecationWarning
    ignore:Attribute n is deprecated and will be removed in Python 3\.14; use value instead:DeprecationWarning
    ignore:.*L-BFGS-B solver are deprecated.*:DeprecationWarning
    ignore:.*deprecated binary model format.*:UserWarning